---
# YAML Lint configuration
# Ignore warnings about GitHub Actions secrets - these are expected
extends: default

rules:
  # Disable warnings about context access (secrets are defined in GitHub)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

